spring.application.name=Payment-Gateway

# Razorpay API Credentials
razorpay.key_id=rzy-key
razorpay.key_secret=rzy-secret key


spring.datasource.url=jdbc:mysql://localhost:3306/pay?createDatabaseIfNotExist=true
spring.datasource.username=sql username
spring.datasource.password=sql passward
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email 
spring.mail.password=your google app
spring.mail.default-encoding=UTF-8

# Additional Engine Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
